steps:
  # Install dependencies
  - name: 'python:3.10'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  # Run scraping script
  - name: 'python:3.10'
    entrypoint: 'python'
    args: ['scrape_aixacademy.py']

  # Run embedding creation script
  - name: 'python:3.10'
    entrypoint: 'python'
    args: ['create_embeddings.py']
    env:
      - 'OPENAI_API_KEY=$_OPENAI_API_KEY'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aixbot', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aixbot']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aixbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aixbot'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/aixbot'

substitutions:
  _OPENAI_API_KEY: ${_OPENAI_API_KEY}

options:
  dynamic_substitutions: true

# Use secret manager to securely pass the OpenAI API key
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/openai_api_key/versions/latest
      env: '_OPENAI_API_KEY'